revision: ""
network: network1
distribution: official

exposeIstiod: true
exposeWebhook: true
exposeClusterServices: true

mode: ACTIVE

runAsRoot: false
metadata:
  labels: {}
  annotations: {}
deployment: {}
service:
  type: LoadBalancer
