version: 2.1
orbs:
  helm: banzaicloud/helm@0.0.8
  docker: banzaicloud/docker@0.0.5

executors:
  helm311:
    docker:
      - image: ghcr.io/banzaicloud/helm:0.0.7

commands:
  publish-with-latests:
    steps:
      - docker/push:
          registry: ghcr.io
          image: banzaicloud/istio-operator
          tag: ${CIRCLE_TAG}
      - docker/version-check:
          version: ${CIRCLE_TAG}
          halt: true
      - run:
          name: Publish latest
          command: |
            minor="$(echo ${CIRCLE_TAG} | cut -d '.' -f2)"
            docker tag "banzaicloud/istio-operator:${CIRCLE_TAG}" "ghcr.io/banzaicloud/istio-operator:latest-1.${minor}"
            docker push "ghcr.io/banzaicloud/istio-operator:latest-1.${minor}"

            latest="$(git tag | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | cut -d '.' -f2 | sort -urn | head -n 1)"
            if [ "${latest}" -eq "${minor}" ]; then
              docker tag "banzaicloud/istio-operator:${CIRCLE_TAG}" "ghcr.io/banzaicloud/istio-operator:latest"
              docker push "ghcr.io/banzaicloud/istio-operator:latest"
            fi

jobs:
  build:
    docker:
    - image: circleci/golang:1.17

    working_directory: /go/src/github.com/banzaicloud/istio-operator
    steps:
    - checkout

    - restore_cache:
        name: Restore build dependencies
        keys:
        - build-deps-v2-{{ .Branch }}-{{ checksum "scripts/download-deps.sh" }}

    - restore_cache:
        name: Restore license cache
        keys:
        - licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
        - licensei-v1-{{ .Branch }}
        - licensei-v1-master
        - licensei-v1

    - run:
        name: Download license information for dependencies
        command: make license-cache

    - save_cache:
        name: Save license cache
        key: licensei-v1-{{ .Branch }}-{{ checksum "go.sum" }}
        paths:
        - .licensei.cache

    - run:
        name: Check dependency licenses
        command: make license-check

    - run:
        name: Run unit tests, linter, etc.
        command: make check

    - run:
        name: Build
        command:
          make build

    - run:
        name: Check that all generated code was checked in to git
        command: make check-all-code-generation

    - save_cache:
        name: Save build dependencies
        key: build-deps-v2-{{ .Branch }}-{{ checksum "scripts/download-deps.sh" }}
        paths:
        - bin/

workflows:
  version: 2
  ci:
    jobs:
    - build

    - docker/build:
        name: Build docker image
        executor: docker/machine-dlc
        image: banzaicloud/istio-operator
        tag: ${CIRCLE_BRANCH//\//-}
        filters:
          tags:
            ignore: /.*/

    - docker/custom-publish:
        name: Publish tagged & latest docker image
        executor: docker/machine-dlc
        context:
          - github
        image: banzaicloud/istio-operator
        login:
          - docker/ghcr-login
        push:
          - publish-with-latests
        filters:
          tags:
            only: /^v?[0-9]+\.[0-9]+\.[0-9]+(?:-(?:dev|rc)\.[0-9]+)?$/
          branches:
            ignore: /.*/

  helm-chart:
    jobs:
      - helm/lint-chart:
          executor: helm311
          charts-dir: deploy/charts
          filters:
            tags:
              ignore: /.*/

      - helm/publish-chart:
          context: helm
          executor: helm311
          charts-dir: deploy/charts
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /deploy\/charts\/v?\d+.\d+.\d+/
