# permissions for end users to view istiocontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiocontrolplane-viewer-role
rules:
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - istiocontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - servicemesh.cisco.com
  resources:
  - istiocontrolplanes/status
  verbs:
  - get
