apiVersion: istio.banzaicloud.io/v1beta1
kind: Istio
metadata:
  name: istio-gw-multi
spec:
  version: "1.9.0-rc.0"
  global: false
  meshPolicy:
    mtlsMode: STRICT
  meshExpansion: true
  imagePullPolicy: Always
  pilot:
    maxReplicas: 1
  istiod:
    multiClusterSupport: true
  gateways:
    ingress:
      maxReplicas: 1
    egress:
      maxReplicas: 1
      enabled: false
