apiVersion: v1
kind: ServiceAccount
{{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istio-reader-service-account" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-reader
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: ServiceAccount
  {{- if .Values.global.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
  {{- end }}
  {{- end }}
metadata:
  name: {{ include "name-with-revision" ( dict "name" "istiod-service-account" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: istiod
    release: {{ .Release.Name }}
---
